services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: medusa
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa
    ports: ["5434:5432"]   # 5434 on host to avoid clashes
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
    healthcheck: { test: ["CMD-SHELL","pg_isready -U medusa -d medusa"], interval: 10s, retries: 6 }

  redis:
    image: redis:7-alpine
    ports: ["6380:6379"]   # 6380 on host to avoid clashes
    command: ["redis-server","--save","","--appendonly","no"]

  meili:
    image: getmeili/meilisearch:v1.7
    environment:
      MEILI_MASTER_KEY: yoursecretmasterkey
    ports: ["7700:7700"]
    volumes: [ "meilidata:/meili_data" ]

volumes:
  pgdata:
  meilidata:
